# Generated by Django 3.1.3 on 2021-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_autho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='autho',
            field=models.CharField(max_length=100),
        ),
    ]
